### ISSUE TITLE
Google Calendar Support

### ISSUE THREAD

**Issue by gregkoss** [RPi-Distro/chromium-browser#1]
Hi,

I think this is a request to use a more current version of Chromium in Raspbian.

The use case is trying to use Google Calendar in the GUI mode.  Chromium 65.X only displays the mobile version.  I'm not sure how current you need to be to support the calendar, but somewhere between v66 and v71 I'm sure it will start working with the GUI.

The workaround is to use Firefox which is terribly slow.  

Thanks for considering this request.
-G

**Comment by spl237** [comment]
We do track Chromium releases - we have to do a fair amount of work to integrate hardware acceleration for video decode with each release, so we are usually a few months behind the current latest Chromium release. We will be updating to a newer release in the next few months, and we will keep making updated releases thereafter - unfortunately I can't give an accurate timescale because it is dependent on what other work we have to resource, but I promise it will happen!
